apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab4.name" . }}-bot
  labels:
    {{- include "lab4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "lab4.name" . }}-bot
  ports:
    - protocol: TCP
      port: {{ .Values.service.botPort }}
      targetPort: {{ .Values.service.botPort }}