apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: schedule_db
  DB_USER: "postgres"
  DB_PASSWORD: "12345"
  BOT_TOKEN: "8650353522:AAGPFqoZaZow-XgnOd5b69mYXaWb1"