replicaCount:
  api: 2
  bot: 1

image:
  repository: lab4-ecommerce
  tag: latest
  pullPolicy: IfNotPresent

resources:
  api:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  bot:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  type: ClusterIP
  apiPort: 8000
  botPort: 8080

env:
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: ecommerce
  DB_HOST: localhost
  DB_PORT: "5432"