name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./lab2
          file: ./lab2/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/ecommerce-app:latest
            ghcr.io/${{ env.OWNER_LC }}/ecommerce-app:sha-${{ github.sha }}

      - name: Scan with Trivy
        run: |
          set +e
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            ghcr.io/${{ env.OWNER_LC }}/ecommerce-app:sha-${{ github.sha }} || true
          rm -f trivy_envs.txt || true

      - name: Run Lab2 test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x lab2/tests/lab2_test.sh
          lab2/tests/lab2_test.sh